### ISSUE TITLE
This branch has not been deployed doesn't change

### ISSUE THREAD

**Issue by ButuzGOL** [shallwefootball/upload-s3-action#16]
May be i am missing something but as i understand it should be changed 
<img width="589" alt="Screen Shot 2020-07-29 at 3 00 13 PM" src="https://user-images.githubusercontent.com/196564/88797658-55a9e880-d1ac-11ea-961f-eb5a43e41722.png">

**Comment by shallwefootball** [comment]
deployment? 
this action is only uploaded at S3 and out url. 

if you want to deployment on Github 
I recommend using this https://github.com/bobheadxi/deployments

**Comment by ButuzGOL** [comment]
Solution was
=> on: [push]
=> target_url changed to environment_url
and it started working
