### ISSUE TITLE
Should also give the ability to upload to a specific directory.

### ISSUE THREAD

**Issue by Aman-RateHub** [shallwefootball/upload-s3-action#2]
The action should also have the ability to provide the destination directory where the data will be stored. 

Would be a nice enhancement.

**Comment by shallwefootball** [comment]
your suggestion is good.

this repository code is very simple. so can you make Pull Request to based on your idea?

**Comment by nionata** [comment]
This would be very useful. Especially for the case of just uploading to the root bucket. I will give this a shot in the next few days and submit a PR. The upload looks very straight forward.
