### ISSUE TITLE
what is this error..? [Repository not found]

### ISSUE THREAD

**Issue by zxczoxc125** [shallwefootball/upload-s3-action#37]
Error: Unable to resolve actions. Repository not found : shallwefootball/s3-upload-action.

**Comment by siennamw** [comment]
Seems like there's confusion between `s3-upload-action` and `upload-s3-action`. I'm seeing it both ways on this page https://github.com/marketplace/actions/upload-s3 right now.  Also the readme shows `shallwefootball/s3-upload-action@master` but the repo URL is `/shallwefootball/upload-s3-action`.  Confusing.

**Comment by zxczoxc125** [comment]
@siennamw thanks!

**Comment by rdominic** [comment]
This appears to have been enforced now, yesterday our builds using `shallwefootball/s3-upload-action` started to fail, changing to `shallwefootball/upload-s3-action` works.
