### ISSUE TITLE
1.3.2 version has critical bug i think

### ISSUE THREAD

**Issue by jkRaccoon** [shallwefootball/upload-s3-action#55]
<img width="678" alt="image" src="https://user-images.githubusercontent.com/13463360/224685948-b802d5cd-e944-4b22-88d2-322fee6787dc.png">

hmm..

**Comment by jkRaccoon** [comment]
@shallwefootball

**Comment by FrancoMartinChattigo** [comment]
I have the same issue

**Comment by FrancoMartinChattigo** [comment]
you can fixed momentarily using v1.3.0 version

**Comment by FranciscoPalaciosChattigo** [comment]
> you can fixed momentarily using v1.3.0 version

you are the best

**Comment by jkRaccoon** [comment]
okay I decided to use temporarily like this.

<img width="388" alt="image" src="https://user-images.githubusercontent.com/13463360/224722355-70c0827f-a6ca-4637-9f83-6f86f1c7cdda.png">

let me know someone fix this issue.

**Comment by ginovski** [comment]
Same on our side, we downgraded and used a fixed version of 1.3.0 as it crashed our deployment

**Comment by travishaby** [comment]
same for us, downgrading to `@v1.3.0`

**Comment by kevinam99** [comment]
Opened https://github.com/shallwefootball/upload-s3-action/pull/56 to fix this
