### ISSUE TITLE
`destination_dir` key warning message

### ISSUE THREAD

**Issue by richardtorres314** [shallwefootball/upload-s3-action#8]
The key `destination_dir` results in the following message:

` ##[warning]Unexpected input 'destination_dir', valid inputs are ['aws_key_id', 'aws_secret_access_key', 'aws_bucket', 'source_dir']`

**Comment by kittaakos** [comment]
Fixed via https://github.com/shallwefootball/upload-s3-action/pull/7? I do not see the warning with `@master` version, but I can confirm, it was there with `@v1.0.1`.

**Comment by shallwefootball** [comment]
try to `v1.1.0` @richardtorres314
